// Auto-generated by Visionary
#![feature(proc_macro_hygiene)]
#![allow(unused_macros, unused_imports)]

mod ken;

#[skyline::main(name = "ky_kiskevisionary_plugin")]
pub fn main() {
    ken::install();
}
